import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import janRouter from "./jan.js";
import uploadRouter from "./upload.js";
import categoriesRouter from "./public/categories.js";
import criteriaRouter from "./public/criteria.js";
import productsRouter from "./public/products.js";
import suggestionsRouter from "./public/suggestions.js";
import fetchUrlRouter from "./public/fetchUrl.js";
import authRouter from "./auth.js";
import userRouter from "./user.js";
import adminAuthRouter from "./admin/auth.js";
import adminCategoriesRouter from "./admin/categories.js";
import adminCriteriaRouter from "./admin/criteria.js";
import adminProductsRouter from "./admin/products.js";
import adminSuggestionsRouter from "./admin/suggestions.js";
import adminUsersRouter from "./admin/users.js";
import adminCategorySuggestionsRouter from "./admin/categorySuggestions.js";
import diagnosisRouter from "./public/diagnosis.js";
import adminTentDiagnosisRouter from "./admin/tentDiagnosis.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(janRouter);
router.use(uploadRouter);
router.use(categoriesRouter);
router.use(criteriaRouter);
router.use(productsRouter);
router.use(suggestionsRouter);
router.use(fetchUrlRouter);
router.use(authRouter);
router.use(userRouter);
router.use(diagnosisRouter);
router.use(adminAuthRouter);
router.use(adminCategoriesRouter);
router.use(adminCriteriaRouter);
router.use(adminProductsRouter);
router.use(adminSuggestionsRouter);
router.use(adminUsersRouter);
router.use(adminCategorySuggestionsRouter);
router.use(adminTentDiagnosisRouter);

export default router;
